[project]
name = "xrf-roi-scan-planner"
version = "0.1.0"
description = "A Python package for finding regions of interest in images."
authors = [{ name = "Ajith Pattammattel" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10,<3.14"
dependencies = [
    "numpy>=1.24",
    "PyQt6",
    "pyqtgraph>=0.13.4",
    "hxntools>=0.6.5,<0.7",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]